#!/usr/bin/env bash

# calcHet
#
# Version 1.0 (25 October, 2016)
# License: GNU GPLv2
# To report bugs or errors, please contact Daren Card (dcard@uta.edu).
# This script is provided as-is, with no support and no guarantee of
# proper or desirable functioning.

# Script that calculates pairise the population genetic statistic
# Pi from a VCF file. This measure represents an approximation based
# only on variant sites (i.e., not standardized by locus length). Users
# may wish to take the average of this measure across reasonable windows
# and can divide by window size to get a more traditional measure of Pi.
#
# User must specify a comma-delimited list of sample IDs
# for the population (must correspond to IDs in VCF),
# the minimum number of sampled alleles in the population (if
# less alleles were sampled, population is considered missing),
# and a VCF file.
#
# This script was created using BCFtools v. 1.3.1, but should work
# with any version > 1. BCFtools must be stored in path as 'bcftools'.
# The VCF file must have the tags AN and AC in the INFO field.
#
# Output is a tab-delimited text file written to STDOUT, with
# the following columns:
# 1. chromosome/scaffold
# 2. variant position
# 3. reference genome allele
# 4. alternative allele
# 5. number of sampled alleles in population
# 6. reference allele frequency in population
# 7. alternative allele frequency in population
# 8. Pi (NA indicates population has too much missing data)
#
# Strict Usage:
# calcFst <pop_list> <pop_n> <variants.vcf>
#
# Example: A populations with two samples (4 alleles),
# where sites with less than 2 sampled alleles (50%) in the 
# population are considered missing.
# calcHet sample1,sample2 2 variants.vcf.gz

bcftools view -s $1 $3 | \
	bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%AN\t%AC\n' - | \
        awk -v OFS="\t" \
                '{ if ($5==0) \
                        print $1,$2,$3,$4,$5,$5,$6; \
                else \
                        print $1,$2,$3,$4,$5,$6/$5,1-($6/$5) }' | \
awk -v OFS="\t" -v x=$2 \
'{ if ($5<x) \
	print $1,$2,$3,$4,$5,$6,$7,$12,$13,$14,"NA"; \
else if ($5>=x) { \
	pi=2*(2*($6*$5)*($7*$5))/($5*($5-1))
	print $1,$2,$3,$4,$5,$6,$7,pi; } }'
